# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-10 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0004_auto_20190110_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='author',
            new_name='user',
        ),
    ]
