# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
